version: '2'

services:
  kube-state-metrics:
    # Build action should be successful from any RHEL Host system running the Docker service with subscription managed registered
    # + info: https://access.redhat.com/solutions/253273
    build: .
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - kube-state-metrics_data:/bitnami
volumes:
  kube-state-metrics_data:
    driver: local
